### ISSUE TITLE
How to process the return value of PartitionBy

### ISSUE THREAD

**Issue by plastikfan** [samber/lo#253]
using the documented example:

```go
import lo "github.com/samber/lo"

partitions := lo.PartitionBy[int, string]([]int{-2, -1, 0, 1, 2, 3, 4, 5}, func(x int) string {
    if x < 0 {
        return "negative"
    } else if x%2 == 0 {
        return "even"
    }
    return "odd"
})
// [][]int{{-2, -1}, {0, 2, 4}, {1, 3, 5}}
```

to me the return value is not particularly useful as you dont know how each sub slice is categorised. If you were to range over the result with each element being a sub slice, how do you know which are the even numbers, the odd and the negative?

In this example, I would have expected ___PartitionBy___ to return a `map[string][]int`, that way, you could index into the returned value with "negative", "even" or "odd" and get the appropriate slice.

I have taken a look at the [lodash](https://lodash.com/docs/4.17.15#partition) version and have found it also is afflicted with the same deficiency. But I may be missing something here so would appreciate being enlightened. Thanks.

**Comment by samber** [comment]
Hi @plastikfan 

You should use GroupBy instead ;)

```go
import lo "github.com/samber/lo"

groups := lo.GroupBy[int, int]([]int{0, 1, 2, 3, 4, 5}, func(i int) int {
    return i%3
})
// map[int][]int{0: []int{0, 3}, 1: []int{1, 4}, 2: []int{2, 5}}
```

**Comment by plastikfan** [comment]
Great thanks

**Comment by lelandbatey** [comment]
Just a note here for my future self: `PartitionBy` is superior to GroupBy in the specific case where you care about the ordering (such as when iterating through the result rows of a long join in SQL), and you can solve the problem of "how do you know how to categorize the subgroups?" by examining the first item in each subgroup, an operation that's ALWAYS safe because `PartitionBy()` will not return sub-slices which are empty; every subslice will have at least one item in it.  [Example:](https://go.dev/play/p/tgsuTy882Rf)

```go
package main

import (
	"fmt"

	"github.com/samber/lo"
)

type OrderItem struct {
	OrderID   int
	ProductID int
	Quantity  int
}

func main() {
	items := []OrderItem{
		{OrderID: 1, ProductID: 101, Quantity: 2},
		{OrderID: 1, ProductID: 102, Quantity: 1},
		{OrderID: 2, ProductID: 103, Quantity: 3},
		{OrderID: 2, ProductID: 104, Quantity: 1},
		{OrderID: 3, ProductID: 101, Quantity: 2},
	}
	orderGroups := lo.PartitionBy(items, func(item OrderItem) int {
		return item.OrderID
	})
	for _, group := range orderGroups {
		orderID := group[0].OrderID
		fmt.Printf("Paritioned Order %d has %d items\n", orderID, len(group))
	}
	for orderID, group := range lo.GroupBy(items, func(item OrderItem) int {
		return item.OrderID
	}) {
		fmt.Printf("GroupBy-ed Order %d has %d items\n", orderID, len(group))
	}
}

/* Prints:
Paritioned Order 1 has 2 items
Paritioned Order 2 has 2 items
Paritioned Order 3 has 1 items
GroupBy-ed Order 2 has 2 items //
GroupBy-ed Order 3 has 1 items // Out of order processing
GroupBy-ed Order 1 has 2 items //
*/
```

This is really best with structs since you're probably partitioning by a specific field you can just access directly after the fact.
