### ISSUE TITLE
Why Async doesn't close a chan? 

### ISSUE THREAD

**Issue by yonesko** [samber/lo#436]
```golang
// Async executes a function in a goroutine and returns the result in a channel.
func Async[A any](f func() A) <-chan A {
	ch := make(chan A, 1)
	go func() {
		ch <- f()
	}()
	return ch
}

```
Why Async doesn't close the chan?

**Comment by ivila** [comment]
Because the chan could be garbage collected automatically when no one cares about it.
the chan have capacity of 1 due to its declaration
```golang
ch := make(chan A, 1)
```
so the method f must can pass value into this chan without any blocking, and after passing value into the chan, the method cares the chan no more.
```golang
        // this line of code must can execute
	go func() {
		ch <- f()
	}()
```
and if anyone listening to the chan outside, they can read it, after they stop reading, then there is no one cares about the chan anymore, in that case, the chan will be garbage collected automatically
