### ISSUE TITLE
go-funk included when vendoring due to usage in benchmark

### ISSUE THREAD

**Issue by jondot** [samber/lo#50]
Hi,
Moving from `go-funk` to `lo`, just noticed `go-funk` is still included in my dependency graph, probably due to it being a dependency for the benchmark suite in `lo`.
Not sure, but is there any way to remove it from the 'release' lib?

**Comment by wirekang** [comment]
Have you tried `go mod tidy`?

**Comment by samber** [comment]
Many libraries are added: testify (+ dependencies), go-funk (+ dependencies)...

I agree with you, we should distribute a clean release of this library.

I think the best way to achieve it, is to move test files into a dedicated module.

**Comment by sergeykonkin** [comment]
Hey guys. Just checked on this and I don't see any test dependecies in vedored packages (probably due to module graph pruning introduced in 1.17 https://go.dev/ref/mod#graph-pruning)

<img width="911" alt="image" src="https://user-images.githubusercontent.com/7695130/202811517-884dadc4-099f-4488-8258-14d326f73702.png">

**Comment by samber** [comment]
Did you check go.sum ?

**Comment by sergeykonkin** [comment]
Yeah, my bad. go.sum contains all deps:

![image](https://user-images.githubusercontent.com/7695130/203004286-0704a55d-7836-4ea3-bf22-3a84b902a286.png)
